repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: .venv/bin/isort
        args: ["."]
        language: system
        pass_filenames: false

      - id: black
        name: black
        entry: .venv/bin/black
        args: ["."]
        language: system
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: .venv/bin/flake8
        args: ["."]
        language: system
        pass_filenames: false

      - id: pylint
        name: pylint
        entry: .venv/bin/pylint
        args: ["intersdk"]
        language: system
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: .venv/bin/mypy
        args: ["."]
        language: system
        pass_filenames: false

      - id: refurb
        name: refurb
        entry: .venv/bin/refurb
        args: ["."]
        language: system
        pass_filenames: false

      - id: pyupgrade
        name: pyupgrade
        entry: .venv/bin/pyupgrade
        language: system
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: .venv/bin/pytest
        args: ["--cov", "--cov-report=html"]
        language: system
        pass_filenames: false
