from typing import Literal

Uf = Literal[
    "AC",
    "AL",
    "AP",
    "AM",
    "BA",
    "CE",
    "DF",
    "ES",
    "GO",
    "MA",
    "MT",
    "MS",
    "MG",
    "PA",
    "PB",
    "PR",
    "PE",
    "PI",
    "RJ",
    "RN",
    "RS",
    "RO",
    "RR",
    "SC",
    "SP",
    "SE",
    "TO",
]
TipoSituacao = Literal["EXPIRADO", "VENCIDO", "EMABERTO", "PAGO", "CANCELADO"]
MotivoCancelamento = Literal["ACERTOS", "APEDIDODOCLIENTE", "PAGODIRETOAOCLIENTE", "SUBSTITUICAO"]
TokenScope = Literal[
    "extrato.read",
    "boleto-cobranca.read",
    "boleto-cobranca.write",
    "pagamento-boleto.write",
    "pagamento-boleto.read",
    "pagamento-darf.write",
    "cob.write",
    "cob.read",
    "cobv.write",
    "cobv.read",
    "pix.write",
    "pix.read",
    "webhook.read",
    "webhook.write",
    "payloadlocation.write",
    "payloadlocation.read",
    "pagamento-pix.write",
    "pagamento-pix.read",
    "webhook-banking.write",
    "webhook-banking.read",
]
